server:
  port: 9001
  servlet:
    context-path: /hzh-user
spring:
  datasource:
    url: jdbc:mysql://192.168.195.131:3306/hzh_tsfse_cloud?useOldAliasMetadataBehavior=true&useSSL=false&serverTimezone=GMT
    username: root
    password: 5q6W7e8R
    driver-class-name: com.mysql.cj.jdbc.Driver
  shardingsphere:
    sharding:
      default-database-strategy:
      tables:

#  # 邮件发送
  mail:
    host: smtp.qq.com
    port: 465
    username: 1391210212@qq.com
#    password: Asdfghjkl629...
    password: qyfdrxqdfumbibfb
    default-encoding: UTF-8
    protocol: smtps


  redis:
    # redis数据库索引(默认为0)，我们使用索引为3的数据库，避免和其他数据库冲突
    database: 0
    # redis服务器地址（默认为loaclhost）
    host: 192.168.195.131
    # redis端口（默认为6379）
    port: 6379
    pool:
      # 最大可用连接数（默认为8，负数表示无限）
      max-active: 8
      #最大空闲连接数（默认为8，负数表示无限）
      max-idle: 8
      # 最小空闲连接数（默认为0，该值只有为正数才有用）
      min-idle: 0
      # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
      max-wait: -1

mybatis-plus:
  type-aliases-package: com.hzh.common.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true



#配置种有共有属性----优先级  服务名-profile.yaml  >  服务名.yaml  >  本地配置
# 优先级即                当前环境配置          >  共享环境配置   >  本地配置
pattern:
  name: 本地环境local